#!/bin/bash

# Author: Savitoj Singh <savitojs@gmail.com>
# Nagios Usage: check_nrpe!_First Attr_!_Second Attr_
# Nagios Usage: check_nrpe!check_docker_container_status!_container_id_
# Usage: ./check_docker_container_status <container_id>
#
# The script checks if a container is running.
#   OK - running
#   CRITICAL - container is stopped
#   UNKNOWN - does not exist

CONTAINER=$1

hash docker 2>/dev/null || { echo "UNKNOWN - docker command not found"; exit 3; }

RUNNING=$(docker inspect --format="{{ .State.Running }}" $CONTAINER 2> /dev/null)

if [ $? -eq 1 ]; then
  echo "UNKNOWN - $CONTAINER container does not exist or container name not provided."
  exit 3
fi

if [ "$RUNNING" == "false" ]; then
  echo "CRITICAL - $CONTAINER is not running."
  exit 2
fi

STARTED=$(docker inspect --format="{{ .State.StartedAt }}" $CONTAINER)
NETWORK=$(docker inspect --format="{{ .NetworkSettings.IPAddress }}" $CONTAINER)

echo "OK - $CONTAINER is running. IP: $NETWORK, StartedAt: $STARTED"
